### PR TITLE
Allow sending id from route

### PR DESCRIPTION
**Pull request by forgandenny**
This would allow custom downloads route, e.g. 

`'download/(?P<id>\d+)' => array('action' => 'supercoolTools/downloadFile')`

### CODE REVIEW

**Comment by joshangell** [comment]
Hi @forgandenny thanks for this, is there a particular reason you want to do it this way rather than with a GET parameter?

**Comment by forgandenny** [comment]
Hi @joshangell -- to be able to build RESTful URLs such as document/345

**Comment by forgandenny** [comment]
Added another commit for fixing an entirely different issue... got added to the same pull request.

**Comment by joshangell** [comment]
OK well that sounds reasonable, I'll take a look when we next release - thanks!

**Pull request closed without merging**
